### ISSUE TITLE
In PIPE mode, sensor web shall catch "disconnection" and "connection" of the PIPE line

### ISSUE THREAD

**Issue by kasumidan** [t2t-io/toe-example-plugins#4]
For example, in case of disconnection, sensor web shall send alert to cloud because this means something wrong with device controller; and in case of connection or reconnection, sensor web shall let device to send meta data again.

**Comment by yagamy4680** [comment]
In TicTacToe design, when the `state` of peripheral object is changed (from **managed** to **configured**, or from **configured** to **managed**), ToeAgent on the device is responsible for sending these state change events (with metadata) to Tic/DM server. TicTacToe's licensee can listen the state change events from Tic/DM server with [tic-dm-client](https://github.com/t2t-io/tic-dm-client).

So, peripheral-service is responsible for emitting the state changes of each individual peripheral object to SensorWeb. For example, one peripheral-service subscribes 2 pipe connections (`C0`, `C1`), and each pipe connection manages 3 peripheral-objects (`PO0` ~ `PO2`, and `PO3` ~ `PO5`), then

1. When `C0` is disconnected, peripheral-service shall emit state change event with **configured** for PO0~2.
2. When `C0` is connected again, and peripheral-service handshakes with PO0 ~ 2 successfully, peripheral-service shall emit state change event with **managed** for PO0 ~ 2.
3. When `C0` is still connected, but there is no response for ping packet (through `C0` connection) for PO1,  peripheral-service shall emit state change event with **configured** for PO1. (Please note, PO0 and PO2 are still in **managed** state at the same time).
4. Repeat above situation but another pipe connection.

BTW, we'd like to suggest peripheral-service can embed the root cause of state change into the metadata json object when emitting the event to SensorWeb, for example:

- `"event_root_cause": "pipe-disconnected"`
- `"event_root_cause": "ping-timeout"`

**Comment by yagamy4680** [comment]
@kasumidan btw, if you really want to send pipe disconnection event to your backend cloud server, it's suggested to send such event in ToeAgent plugin, because in TOE design principle, SensorWeb shall be isolated from cloud and play as a thin abstract layer between control logics (as ToeAgent plugin) and low level drivers. If you prefer this way, we can add `pipe-connection-changed` event to ToeAgent for plugin development. How do you think?

**Comment by kasumidan** [comment]
I just realized that I can use `atPipeEstablished` and `atPipeDisconnected` to detect connection and disconnection.  

For cloud notification, I added a p_type `device_controller` and `connection_status` sensor to record the connection changing.

Therefore, I will withdraw this issue.
